[package]
name = "query-engine-wasm-api"
version = "0.1.0"
edition = "2021"

[lib]
doc = false
crate-type = ["cdylib"]
name = "libquery_wasm"

[features]
default = ["js-connectors"]
js-connectors = ["request-handlers/js-connectors", "sql-connector/js-connectors"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
query-core = { path = "../core", default-features = false }
request-handlers = { path = "../request-handlers", default-features = false, features = ["js-connectors", "sql"] }
query-connector = { path = "../connectors/query-connector", default-features = false }
user-facing-errors = { path = "../../libs/user-facing-errors", features = ["quaint"] }
psl.workspace = true
sql-connector = { path = "../connectors/sql-query-connector", package = "sql-query-connector", default-features = false, features = ["js-connectors"] }
prisma-models = { path = "../prisma-models", default-features = false, features = ["wasm_generators"] }
wasm-connectors = { path = "../wasm-connectors" }
quaint = { path = "../../quaint", features = ["slim"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3" }
tracing-futures = "0.2"

thiserror = "1"
connection-string.workspace = true
url = "2"
serde_json.workspace = true
serde.workspace = true
tokio = { version = "1.25", features = ["rt", "macros", "sync", "io-util", "time"] }
futures = "0.3"
console_error_panic_hook = "*"

wasm-bindgen = "=0.2.84"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.5"
serde_repr = "0.1"
js-sys = "0.3"

[profile.release]
# Default release settings for all targets

[profile.release.target.'cfg(target_arch = "wasm32")']
# Custom release settings for wasm32-unknown-unknown
opt-level = "z"
lto = "fat"
panic = "abort"
