[package]
edition = "2021"
name = "sql-query-connector"
version = "0.1.0"

[features]
vendored-openssl = ["quaint/vendored-openssl"]
js-connectors = []
native-connectors = ["cuid", "connector-interface/native", "quaint/pooled", "quaint/connectors"]
default = ["native-connectors"]

[dependencies]
psl.workspace = true
anyhow = "1.0"
async-trait = "0.1"
bigdecimal = "0.3"
futures = "0.3"
itertools = "0.10"
once_cell = "1.3"
rand = "0.7"
serde_json = {version = "1.0", features = ["float_roundtrip"]}
thiserror = "1.0"
tokio = { version = "1.25", features = ["rt", "macros", "sync", "io-util", "time"] }
tracing = "0.1"
tracing-futures = "0.2"
uuid.workspace = true
opentelemetry = { version = "0.17", features = ["tokio"] }
tracing-opentelemetry = "0.17.3"
quaint = { path = "../../../quaint", features = ["slim"] }

[dependencies.connector-interface]
package = "query-connector"
path = "../query-connector"
default-features = false

[dependencies.prisma-models]
path = "../../prisma-models"

[dependencies.prisma-value]
path = "../../../libs/prisma-value"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.cuid]
version = "1.2"
optional = true

[dependencies.user-facing-errors]
features = ["sql"]
path = "../../../libs/user-facing-errors"
